export const GENERATORS = [
  { id: "plasma", name: "Lava", osc: "/intersect/generator/plasma" },
  { id: "voronoi", name: "Cell Grid", osc: "/intersect/generator/voronoi" },
  { id: "reaction_diffusion", name: "Living Cells", osc: "/intersect/generator/reaction_diffusion" },
  { id: "star_tunnel", name: "Warp Speed", osc: "/intersect/generator/star_tunnel" },
  { id: "perlin_flow", name: "Smoke", osc: "/intersect/generator/perlin_flow" },
  { id: "fractal", name: "Infinite", osc: "/intersect/generator/fractal" },
  { id: "lissajous", name: "Frequencies", osc: "/intersect/generator/lissajous" },
  { id: "truchet", name: "Labyrinth", osc: "/intersect/generator/truchet" },
  { id: "matrix", name: "The Matrix", osc: "/intersect/generator/matrix" },
  { id: "linescape", name: "Horizon", osc: "/intersect/generator/linescape" },
  { id: "deep_space", name: "Deep Space", osc: "/intersect/generator/deep_space" },
  { id: "vortex", name: "Black Hole", osc: "/intersect/generator/vortex" },
  { id: "noise", name: "Static", osc: "/intersect/generator/noise" },
  { id: "plasma_globe", name: "Tesla", osc: "/intersect/generator/plasma_globe" },
  { id: "menger", name: "Cube God", osc: "/intersect/generator/menger" },
];

export const EFFECTS = [
  { id: "kaleidoscope", name: "Mirror Fold", osc: "/intersect/fx/kaleidoscope" },
  { id: "feedback_echo", name: "Ghost Trails", osc: "/intersect/fx/feedback_echo" },
  { id: "rgb_shift", name: "Color Split", osc: "/intersect/fx/rgb_shift" },
  { id: "pixel_sort", name: "Digital Melt", osc: "/intersect/fx/pixel_sort" },
  { id: "datamosh", name: "Glitch", osc: "/intersect/fx/datamosh" },
  { id: "mirror", name: "Symmetry", osc: "/intersect/fx/mirror" },
  { id: "edge_detect", name: "Wireframe", osc: "/intersect/fx/edge_detect" },
  { id: "bloom", name: "Glow", osc: "/intersect/fx/bloom" },
  { id: "vignette", name: "Frame", osc: "/intersect/fx/vignette" },
  { id: "blur", name: "Blur", osc: "/intersect/fx/blur" },
  { id: "strobe", name: "Strobe", osc: "/intersect/fx/strobe" },
  { id: "invert", name: "Invert", osc: "/intersect/fx/invert" },
  { id: "hue_rotate", name: "Color Spin", osc: "/intersect/fx/hue_rotate" },
  { id: "vhs", name: "VHS", osc: "/intersect/fx/vhs" },
  { id: "fisheye", name: "Fisheye", osc: "/intersect/fx/fisheye" },
  { id: "halftone", name: "Dots", osc: "/intersect/fx/halftone" },
  { id: "posterize", name: "Flat", osc: "/intersect/fx/posterize" },
  { id: "scanlines", name: "CRT", osc: "/intersect/fx/scanlines" },
  { id: "solarize", name: "Solar", osc: "/intersect/fx/solarize" },
  { id: "blowout", name: "Blow Out", osc: "/intersect/fx/blowout" },
  { id: "rutt_etra", name: "Wireframe 3D", osc: "/intersect/fx/rutt_etra" },
  { id: "optical_flow", name: "Liquid Motion", osc: "/intersect/fx/optical_flow" },
  { id: "glitch_morph", name: "Morph", osc: "/intersect/fx/glitch_morph" },
  { id: "time_glitch", name: "Rainbow Ghost", osc: "/intersect/fx/time_glitch" },
  { id: "displacement", name: "Warp", osc: "/intersect/fx/displacement" },
  { id: "audio_warp", name: "Audio Warp", osc: "/intersect/fx/audio_warp" },
  { id: "zoom_blur", name: "Rush", osc: "/intersect/fx/zoom_blur" },
  { id: "swirl", name: "Vortex", osc: "/intersect/fx/swirl" },
  { id: "freeze", name: "Freeze", osc: "/intersect/fx/freeze" },
  { id: "stretch", name: "Stretch", osc: "/intersect/fx/stretch" },
  { id: "tunnel", name: "Tunnel", osc: "/intersect/fx/tunnel" },
  { id: "datamelt", name: "Datamelt", osc: "/intersect/fx/datamelt" },
  { id: "cell_shatter", name: "Cell Shatter", osc: "/intersect/fx/cell_shatter" },
];

export const CHAINS = [
  { id: "acid_spiral", name: "Acid Spiral", fx: ["kaleidoscope", "feedback_echo", "hue_rotate", "rgb_shift", "vignette"] },
  { id: "glitch_god", name: "Glitch God", fx: ["pixel_sort", "datamosh", "invert", "rgb_shift", "scanlines"] },
  { id: "neon_ghost", name: "Neon Ghost", fx: ["edge_detect", "feedback_echo", "bloom", "vignette"] },
  { id: "cyber_tunnel", name: "Cyber Tunnel", fx: ["vhs", "kaleidoscope", "tunnel", "rgb_shift"] },
  { id: "audio_melt", name: "Audio Melt", fx: ["audio_warp", "rgb_shift", "bloom", "blur"] },
  { id: "afterlife", name: "Afterlife", fx: ["feedback_echo", "hue_rotate", "vignette", "bloom", "mirror"] },
  { id: "cosmic_cathedral", name: "Cosmic Cathedral", generator: "voronoi", fx: ["kaleidoscope", "feedback_echo", "edge_detect", "hue_rotate", "vignette"] },
  { id: "rutt_etra_machine", name: "Rutt-Etra Machine", fx: ["rutt_etra", "kaleidoscope", "rgb_shift", "vignette"] },
  { id: "clean_cinema", name: "Clean Cinema", fx: ["vignette", "blur", "bloom", "rgb_shift"] },
  { id: "neon_punch", name: "Neon Punch", fx: ["edge_detect", "blowout", "bloom", "vignette"] },
  { id: "solar_burn", name: "Solar Burn", fx: ["solarize", "hue_rotate", "blowout", "vignette"] },
  { id: "deep_freeze", name: "Deep Freeze", fx: ["freeze", "mirror", "rgb_shift", "blur"] },
  { id: "psychedelic", name: "Psychedelic", generator: "fractal", fx: ["kaleidoscope", "hue_rotate", "fisheye", "feedback_echo"] },
  { id: "bass_drop", name: "Bass Drop", fx: ["datamosh", "pixel_sort", "strobe", "invert"] },
  { id: "dreamscape", name: "Dreamscape", generator: "perlin_flow", fx: ["feedback_echo", "blur", "hue_rotate", "bloom"] },
];

export const AUDIO_MAPPINGS = [
  { id: "kick_scale", name: "Kick pumps the size", osc: "/intersect/audio/kick_scale" },
  { id: "bass_kaleido", name: "Bass spins the mirror", osc: "/intersect/audio/bass_kaleido" },
  { id: "bass_feedback", name: "Bass → Feedback Opacity", osc: "/intersect/audio/bass_feedback" },
  { id: "mid_chroma", name: "Mid → Chromatic Aberration", osc: "/intersect/audio/mid_chroma" },
  { id: "mid_pixelsort", name: "Mid → Pixel Sort Threshold", osc: "/intersect/audio/mid_pixelsort" },
  { id: "high_hue", name: "High → Hue Rotation Speed", osc: "/intersect/audio/high_hue" },
  { id: "high_brightness", name: "High → Brightness", osc: "/intersect/audio/high_brightness" },
  { id: "amp_vignette", name: "Overall → Vignette Intensity", osc: "/intersect/audio/amp_vignette" },
  { id: "bpm_strobe", name: "BPM → Strobe Rate", osc: "/intersect/audio/bpm_strobe" },
  { id: "bpm_invert", name: "BPM → Color Invert Trigger", osc: "/intersect/audio/bpm_invert" },
];

export const BLEND_MODES = [
  { id: "add", name: "Neon", osc: "/intersect/blend/add" },
  { id: "screen", name: "Overlay", osc: "/intersect/blend/screen" },
  { id: "multiply", name: "Dark", osc: "/intersect/blend/multiply" },
  { id: "difference", name: "Psychedelic", osc: "/intersect/blend/difference" },
  { id: "overlay", name: "Punch", osc: "/intersect/blend/overlay" },
  { id: "normal", name: "Clean", osc: "/intersect/blend/normal" },
];

export const MASTER_CONTROLS = [
  { id: "opacity", name: "Master Opacity", osc: "/intersect/master/opacity" },
  { id: "feedback", name: "Feedback", osc: "/intersect/master/feedback" },
  { id: "color", name: "Color", osc: "/intersect/master/color" },
];
